<?php
// template-parts/home/categories-section.php
$cats = get_terms( [
	'taxonomy'   => 'app-category',
	'hide_empty' => true,
	'number'     => 12,
	'orderby'    => 'count',
	'order'      => 'DESC',
] );
?>
<?php if ( $cats && ! is_wp_error( $cats ) ) : ?>
<section class="tc-page pas-reveal">
	<div class="container">
		<div class="section-title-row">
			<div>
				<div class="tc-eyebrow"><?php esc_html_e( 'Browse', 'appstorepro' ); ?></div>
				<h2 class="tc-title"><?php esc_html_e( 'Categories', 'appstorepro' ); ?></h2>
			</div>
			<a href="<?= esc_url( home_url( '/app-category/' ) ); ?>" class="section-view-all"><?php esc_html_e( 'All categories', 'appstorepro' ); ?> &rarr;</a>
		</div>
		<div class="tc-grid">
			<?php foreach ( $cats as $cat ) :
				$icon_slug = $cat->slug;
				$svg       = appstorepro_get_category_icon_svg( $icon_slug );
				?>
				<a href="<?= esc_url( get_term_link( $cat ) ); ?>" class="tc-card">
					<div class="tc-card-icon">
						<?= $svg; // SVG is generated by our function, safe to echo ?>
					</div>
					<div class="tc-card-info">
						<div class="tc-card-name"><?= esc_html( $cat->name ); ?></div>
						<div class="tc-card-count"><?= esc_html( $cat->count ); ?> <?php esc_html_e( 'apps', 'appstorepro' ); ?></div>
					</div>
					<span class="tc-card-arrow">
						<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" width="14" height="14">
							<polyline points="9 18 15 12 9 6"/>
						</svg>
					</span>
				</a>
			<?php endforeach; ?>
		</div>
	</div>
</section>
<?php endif; ?>
